// One-off: bake a large offline catalog from the production TMDB proxy so
// local/dev (no TMDB key) still has hundreds of real titles — movies, TV,
// K/C/J-dramas, cartoons, famous shows.
// Usage: node scripts/fetch-catalog.mjs [BASE_URL]
const BASE = process.argv[2] || 'https://muragoods.vercel.app';

const jobs = [
  ['popMovies', '/api/murastream/tmdb?action=popular&type=movie', 15],
  ['topMovies', '/api/murastream/tmdb?action=top_rated&type=movie', 5],
  ['popTV', '/api/murastream/tmdb?action=popular&type=tv', 15],
  ['topTV', '/api/murastream/tmdb?action=top_rated&type=tv', 5],
  ['kdrama', '/api/murastream/tmdb?action=discover&type=tv&with_original_language=ko&with_genres=18&vote_count_gte=20', 10],
  ['cdrama', '/api/murastream/tmdb?action=discover&type=tv&with_original_language=zh&with_genres=18&vote_count_gte=20', 5],
  ['jdrama', '/api/murastream/tmdb?action=discover&type=tv&with_original_language=ja&with_genres=18&vote_count_gte=20', 5],
  ['cartoonMovies', '/api/murastream/tmdb?action=discover&type=movie&with_genres=16&vote_count.gte=200', 5],
  ['cartoonTV', '/api/murastream/tmdb?action=discover&type=tv&with_genres=16&vote_count.gte=100', 5],
  ['famousTV', '/api/murastream/tmdb?action=discover&type=tv&vote_count.gte=1000', 5],
];

const out = {};
const seen = new Set();

for (const [key, path, pages] of jobs) {
  const items = [];
  for (let p = 1; p <= pages; p++) {
    const sep = path.includes('?') ? '&' : '?';
    const res = await fetch(`${BASE}${path}${sep}page=${p}`).catch(() => null);
    if (!res || !res.ok) { console.error(`FAIL ${key} p${p}`); continue; }
    const d = await res.json();
    for (const r of (d.results || [])) {
      if (seen.has(String(r.id))) continue;
      seen.add(String(r.id));
      items.push({
        id: r.id, mediaType: r.mediaType || 'movie', title: r.title || r.name || 'Untitled',
        year: r.year || '', voteAverage: r.voteAverage ?? 0,
        posterPath: r.posterPath || null, backdropPath: r.backdropPath || null,
        overview: (r.overview || '').slice(0, 300),
        genreIds: (r.genreIds || []).slice(0, 6), originalLanguage: r.originalLanguage || '',
      });
    }
  }
  out[key] = items;
  console.log(`${key}: ${items.length}`);
}

const fs = await import('fs');
const header = `// AUTO-GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
// Large baked-in catalog so local/dev (no TMDB key) still has hundreds of
// real titles across movies, TV, K/C/J-dramas, cartoons and famous shows.
import type { MediaItem } from '../types';

export const BAKED_CATALOG: Record<string, MediaItem[]> = `;
fs.writeFileSync('app/murastream/data/baked-catalog.ts', header + JSON.stringify(out, null, 1) + ';\n');
const total = Object.values(out).reduce((a, b) => a + b.length, 0);
console.log('TOTAL unique:', total);
